name = "Hugo Neo"
license = "MIT"
licenselink = "https://github.com/AravindVasudev/hugo-neo/blob/master/LICENSE"
description = "A simple hugo theme."
homepage = "https://github.com/AravindVasudev/hugo-neo"
tags = ["blog", "neo", "terminal", "coder", "matrix"]
features = []
min_version = "0.41.0"

[author]
  name = "Aravind Vasudevan"
  homepage = "https://aravindvasu.dev/"